CREATE DATABASE M_Livros2;

USE M_Livros2;

CREATE TABLE Generos
(
	IdGenero INT PRIMARY KEY IDENTITY
	,Descricao TEXT NOT NULL
);

CREATE TABLE Autores
(
	IdAutor INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200)UNIQUE NOT NULL
	,Email VARCHAR(200)UNIQUE
	,Ativo CHAR(1) DEFAULT(1)
	,DataNascimento DATE
);



CREATE TABLE Livros
(
	IdLivro INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200)UNIQUE NOT NULL
	,IdAutor INT FOREIGN KEY REFERENCES Autores (IdAutor)
	,IdGenero INT FOREIGN KEY REFERENCES Generos (IdGenero)
);